repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.3.0
      hooks:
          - id: prettier
            name: prettier
            entry: prettier --write --ignore-unknown
            language: node
            'types': [text]
            args: []
